version: "2.1"
services:
  paisa:
    image: ananthakumaran/paisa:latest
    container_name: paisa
    env_file:
      - ../common.env
    environment:
      - PAISA_CONFIG=/root/Documents/paisa.yaml
    expose:
      - 7500
    volumes:
      - "/datadisk/.state/paisa:/root/Documents/paisa/"
      - "/datadisk/.config/paisa/paisa.yaml:/root/Documents/paisa.yaml"
      - "/datadisk/sync/accounting:/root/Documents/ledger/"
    restart: unless-stopped
networks:
  default:
    name: proxy
    external: true
