version: "2.1"
services:
  paisa:
    image: ananthakumaran/paisa:latest
    container_name: paisa
    env_file:
      - ../common.env
    expose:
      - 7500
    volumes:
      - "/datadisk/.state/paisa/:/root/Documents/paisa/"
      - "./paisa.yml:/root/Documents/paisa/paisa.yml"
      - "/datadisk/sync/accounting:/root/Documents/ledger/"
    restart: unless-stopped
networks:
  default:
    name: proxy
    external: true