version: "2.1"
services:
  grafana:
    image: grafana/grafana-oss:main-ubuntu
    container_name: grafana
    user: '1000'
    env_file:
      - ./common.env
    environment:
      - GF_LOG_MODE=console file
    volumes:
      - "/datadisk/config/grafana/var:/var/lib/grafana"
      - "/datadisk/config/grafana/grafana.ini:/conf/grafana.ini"
      - "/datadisk/config/babybuddy/data/:/ds-babybuddy/:ro"
    restart: unless-stopped
    expose:
      - 3000
networks:
  default:
    name: proxy
    external: true
