version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    env_file:
      - ../common.env
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.config/docker/config.json:/config.json
    command: --interval 30
