version: "2.1"
services:
  grocy:
    image: lscr.io/linuxserver/babybuddy:latest
    container_name: babybuddy
    env_file:
      - ../common.env
      - ./common.env
    environment:
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy.kvineet.in
    volumes:
      - "${HOME}/vpc-docker/babybuddy/data/:/config"
    restart: unless-stopped
networks:
  default:
    name: proxy
    external: true
