version: "2.1"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:v1.13.2-ls62
    container_name: babybuddy
    env_file:
      - ../common.env
      - ./common.env
    environment:
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy.kvineet.in
    volumes:
      - "/datadisk/config/babybuddy/:/config"
    restart: unless-stopped
networks:
  default:
    name: proxy
    external: true
