version: '3'

services:
  watchtower:
    image: kylemanna/syncthing-relay
    container_name: syncthing-relay
    env_file:
      - ./common.env
    restart: unless-stopped
    volumes:
      - syncthing-relay:/relaysrv
    command: -pools=""
volumes:
  syncthing-relay:
    external: true