version: "2.1"
services:
  taskd:
    image: ghcr.io/connectical/taskd:latest
    container_name: taskd
    env_file:
      - ../common.env
      - env
    ports:
      - "53589:53589"
    volumes:
      - "/datadisk/config/taskd/:/var/taskd"
    restart: unless-stopped
  webui:
    image: dcsunset/taskwarrior-webui:latest
    container_name: taskwebui
    env_file:
      - ../common.env
    expose:
      - "80"
    networks:
      - proxy
    volumes:
      - "/datadisk/config/taskwebui/taskrc:/.taskrc"
      - "/datadisk/config/taskwebui/task:/.task"
    restart: unless-stopped
networks:
  proxy:
    name: proxy
    external: true
