version: "2.1"
services:
  taskd:
    image: ghcr.io/connectical/taskd:latest
    container_name: babybuddy
    env_file:
      - ../common.env
      - env
    volumes:
      - "/datadisk/config/taskd/:/var/taskd"
    restart: unless-stopped
networks:
  default:
    name: proxy
    external: true
