version: "3.3"

services:
  browsermax:
    image: docker.io/jare/browsermax:latest
    container_name: browsermax
    restart: unless-stopped
    volumes:
      - "${HOME}/vpc-docker/emacs/data/:/home/emacs/.emacs.d/.cache"
    environment:
      APPROXIMATE_MAX_CONNECTION_LENGTH_S: 3600
    ports:
      - 10000:10000
networks: 
  default: 
    external: 
      name: vpc-services
