version: '3'

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    env_file:
      - ../common.env
    restart: unless-stopped
    volumes:
      - /datadisk/.state/syncthing:/config
      - /datadisk/sync:/sync
    expose:
      - 8384
    ports:
      - 22000:22000
      - 21027:21027
networks:
  default:
    name: proxy
    external: true
