version: '3'

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    env_file:
      - ./common.env
    restart: unless-stopped
    volumes:
      - /datadisk/config/syncthing/config:/config
      - /datadisk/sync:/sync
    expose:
      - 8384
      - 22000/tcp
      - 22000/udp
      - 21027/udp